version: "3.8"

services:
  prep:
    env_file:
      - aws.env

  hub:
    env_file:
      - aws.env

  admin:
    env_file:
      - aws.env

  reader:
    env_file:
      - aws.env

  nginx:
    env_file:
      - aws.env
